@startuml
!include theme/base-skin.iuml

note as N1
StorageType
  POSIX
  S3
  OBJECT_STORE
- - - - - - - - - - - - -
SchedulerType
  FORK
  BATCH
  ON_DEMAND
- - - - - - - - - - - - -
SystemType
  LINUX
  WINDOWS
end note

class SGCIResource {
  schemaVersion! : string
  host! : string
  name! : string
  description : string
  storageResources! : StorageResource[]
  computeResources : ComputeResource[]
}

class StorageResource {
  storageType! : enum
  connections! : Connection[]
  fileSystems! : FileSystem[]
  defaultQuota : object
}

class ComputeResource {
  schedulerType! : Enum
  connections! : Connection[]
  batchSystem! : BatchSystem
  forkSystem! : ForkSystem
  executionCommands! : ExecutionCommand[]
}

class Connection {
  connectionProtocol! : Enum
  securityProtocol! : Enum
  port : integer
  useProxy : boolean
  proxyHost : string
  proxyPort : integer
}

class FileSystem {
  mountDir : string
  homeDir : string
  scratchDir : string
  workDir : string
  capacity : object
}

class ExecutionCommand {
  commandType! : string
  commandPrefix : string
  homeDir : string
  moduleDependencies : string[]
}

class BatchSystem {
  jobManager! : Enum
  commandPaths : CommandPath[]
  partitions : Partition[]
}

class ForkSystem {
  systemType! : enum
  version : string
  nodeHardware : NodeHardware
}

class CommandPath {
  name! : string
  path! : string
}

class Partition {
  name! : string
  totalNodes : integer
  nodeHardware : NodeHardware
  computeQuotas : object
}

class NodeHardware {
  cpuType : string
  cpuCount : integer
  gpuType : string
  gpuCount : integer
  memoryType : string
  memorySize : string
}

SGCIResource *-- "1..N" StorageResource
SGCIResource *-- "0..N" ComputeResource
StorageResource *-- "N" Connection
StorageResource *-- "N" FileSystem
ComputeResource *-- "0,1" BatchSystem : OneOf
ComputeResource *-- "0,1" ForkSystem : OneOf
ComputeResource *-- "N" Connection
ComputeResource *-- "N" ExecutionCommand
BatchSystem *-- "N" CommandPath
BatchSystem *-- "N" Partition
Partition *-- "1" NodeHardware
ForkSystem *-- "1" NodeHardware

@enduml