@startuml
!include theme/base-skin.iuml

note as N1
StorageType
  POSIX
  S3
  IRODS
- - - - - - - - - - - - -
SchedulerType
  FORK
  BATCH
  ON_DEMAND
- - - - - - - - - - - - -
SystemType
  LINUX
  WINDOWS
end note

class SGCIResource {
  schemaVersion! : string
  host! : string
  name! : string
  description : string
  storageResources! : StorageResource[]
  computeResources : ComputeResource[]
  resourceStatus : ResourceStatus
  resourceOutages : ResourceOutage[]
}

class ResourceStatus {
  status! : enum
  startDate : string
  endsDate : string
}

class ResourceOutage {
  outageType : enum
  name : string
  description : string
  url : string
  startDatetime! : string
  endsDatetime! : string
}

class StorageResource {
  storageType! : enum
  connections! : Connection[]
  fileSystems! : FileSystem[]
  defaultQuota : object
}

class ComputeResource {
  schedulerType! : Enum
  connections! : Connection[]
  batchSystem! : BatchSystem
  forkSystem! : ForkSystem
  executionCommands : ExecutionCommand[]
}

class Connection {
  connectionProtocol! : Enum
  securityProtocol! : Enum
  host : string
  port : integer
  proxyHost : string
  proxyPort : integer
}

class FileSystem {
  mountDir : string
  homeDir : string
  scratchDir : string
  workDir : string
  capacity : object
}

class ExecutionCommand {
  commandType! : string
  commandPrefix : string
  moduleDependencies : string[]
}

class BatchSystem {
  jobManager! : Enum
  host : string
  commandPaths : CommandPath[]
  partitions : Partition[]
}

class ForkSystem {
  systemType! : enum
  version : string
  nodeHardware : NodeHardware
}

class CommandPath {
  name! : string
  path! : string
}

class Partition {
  name! : string
  submitArgs : string[]
  totalNodes : integer
  nodeHardware : NodeHardware
  computeQuotas : object
}

class NodeHardware {
  cpuType : string
  cpuCount : integer
  gpuType : string
  gpuCount : integer
  memoryType : string
  memorySize : string
}

class ComputeQuotas {
  maxJobsTotal : integer
  maxJobsPerUser : integer
  minNodesPerJob : integer
  maxNodesPerJob : integer
  minTimePerJob : integer
  maxTimePerJob : integer
  minMemoryPerJob : string
  maxMemoryPerJob : string
  minCPUsPerJob : integer
  maxCPUsPerJob : integer
  minGPUsPerJob : integer
  maxGPUsPerJob : integer
  minCPUsPerNode : integer
  maxCPUsPerNode : integer
 }

SGCIResource *-- "1..N" StorageResource
SGCIResource *-- "0..N" ComputeResource
SGCIResource *-- "1" ResourceStatus
SGCIResource *-- "N" ResourceOutage
StorageResource *-- "N" Connection
StorageResource *-- "N" FileSystem
ComputeResource *-- "0,1" BatchSystem : OneOf
ComputeResource *-- "0,1" ForkSystem : OneOf
ComputeResource *-- "N" Connection
ComputeResource *-- "N" ExecutionCommand
BatchSystem *-- "N" CommandPath
BatchSystem *-- "N" Partition
Partition *-- "1" NodeHardware
Partition *-- "1" ComputeQuotas
ForkSystem *-- "1" NodeHardware

@enduml